// Code generated by logcopter-gen; DO NOT EDIT.

package datalab

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("hyperslop-systems.hyperslop-cli.pkg.datalab")
