// Code generated by logcopter-gen; DO NOT EDIT.

package authcmd

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("hyperslop-systems.hyperslop-cli.pkg.cli.authcmd")
